// <auto-generated />
using System;
using EduApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduApplication.Migrations
{
    [DbContext(typeof(EduApplicationContext))]
    partial class EduApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduApplication.Models.Alphabet", b =>
                {
                    b.Property<int>("letter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("letter_id"));

                    b.Property<string>("audio_url")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("letter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("photo_url")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("letter_id")
                        .HasName("PK__Alphabet__A6F3C31C44939557");

                    b.HasIndex("category_id");

                    b.HasIndex(new[] { "letter" }, "UQ__Alphabet__853DC438315AEE15")
                        .IsUnique();

                    b.ToTable("Alphabets");
                });

            modelBuilder.Entity("EduApplication.Models.Animal", b =>
                {
                    b.Property<int>("animal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("animal_id"));

                    b.Property<string>("animal_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("audio_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("animal_id")
                        .HasName("PK__Animals__DE680F9270C62114");

                    b.HasIndex("category_id");

                    b.HasIndex(new[] { "animal_name" }, "UQ__Animals__FB9F6D4C77F05DB0")
                        .IsUnique();

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("EduApplication.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("category_id")
                        .HasName("PK__Category__D54EE9B456306F9F");

                    b.HasIndex(new[] { "category_name" }, "UQ__Category__5189E255AC09005F")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("EduApplication.Models.Child", b =>
                {
                    b.Property<int>("child_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("child_id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("child_id")
                        .HasName("PK__Children__015ADC0512E1D134");

                    b.HasIndex("parent_id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("EduApplication.Models.Child_Content", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("child_id")
                        .HasColumnType("int");

                    b.Property<int>("content_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__Child_Co__3213E83F4D9B9CC0");

                    b.HasIndex("category_id");

                    b.HasIndex("child_id");

                    b.ToTable("Child_Content", (string)null);
                });

            modelBuilder.Entity("EduApplication.Models.Number", b =>
                {
                    b.Property<int>("number_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("number_id"));

                    b.Property<string>("audio_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("number_value")
                        .HasColumnType("int");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("number_id")
                        .HasName("PK__Numbers__4BE613D35F479957");

                    b.HasIndex("category_id");

                    b.HasIndex(new[] { "number_value" }, "UQ__Numbers__2C8F03EC91AC93AB")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("EduApplication.Models.Story", b =>
                {
                    b.Property<int>("story_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("story_id"));

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("video_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("story_id")
                        .HasName("PK__Stories__66339C5643A8DF6C");

                    b.HasIndex("category_id");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Parents", b =>
                {
                    b.Property<int>("parent_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("parent_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("otp")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("otp_expiration_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("parent_id")
                        .HasName("PK__Parents__F2A60819CB14ED86");

                    b.HasIndex(new[] { "email" }, "UQ__Parents__AB6E616432BAB267")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("EduApplication.Models.Alphabet", b =>
                {
                    b.HasOne("EduApplication.Models.Category", "category")
                        .WithMany("Alphabets")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Alphabets__categ__412EB0B6");

                    b.Navigation("category");
                });

            modelBuilder.Entity("EduApplication.Models.Animal", b =>
                {
                    b.HasOne("EduApplication.Models.Category", "category")
                        .WithMany("Animals")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Animals__categor__48CFD27E");

                    b.Navigation("category");
                });

            modelBuilder.Entity("EduApplication.Models.Child", b =>
                {
                    b.HasOne("Parents", "parent")
                        .WithMany("Children")
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Children__parent__3D5E1FD2");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("EduApplication.Models.Child_Content", b =>
                {
                    b.HasOne("EduApplication.Models.Category", "category")
                        .WithMany("Child_Contents")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Child_Con__categ__4F7CD00D");

                    b.HasOne("EduApplication.Models.Child", "child")
                        .WithMany("Child_Contents")
                        .HasForeignKey("child_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Child_Con__child__4E88ABD4");

                    b.Navigation("category");

                    b.Navigation("child");
                });

            modelBuilder.Entity("EduApplication.Models.Number", b =>
                {
                    b.HasOne("EduApplication.Models.Category", "category")
                        .WithMany("Numbers")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Numbers__categor__44FF419A");

                    b.Navigation("category");
                });

            modelBuilder.Entity("EduApplication.Models.Story", b =>
                {
                    b.HasOne("EduApplication.Models.Category", "category")
                        .WithMany("Stories")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Stories__categor__4BAC3F29");

                    b.Navigation("category");
                });

            modelBuilder.Entity("EduApplication.Models.Category", b =>
                {
                    b.Navigation("Alphabets");

                    b.Navigation("Animals");

                    b.Navigation("Child_Contents");

                    b.Navigation("Numbers");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("EduApplication.Models.Child", b =>
                {
                    b.Navigation("Child_Contents");
                });

            modelBuilder.Entity("Parents", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
